### ISSUE TITLE
Possible to run non-GPU version on apple silicon?

### ISSUE THREAD

**Issue by hyanwong** [jthlab/phlash#2]
Just for kicks, I wondered if I could run phlash on my M2 MacBook (with the expectation of it being slow, as I'm assuming it won't use the GPU version). it looks like https://github.com/jthlab/phlash/commit/fa8c523380fbc84a60cea5c4d23527a30bc2488c is intended to allow running on machines without a compatible GPU, but there's still a [CUDA requirement](https://github.com/jthlab/phlash/blob/8eb2a550c86c68f2f81822bf0881f117f52d36a0/pyproject.toml#L10) in the installation spec, so when I install from pip, I'm getting:

```
pip install phlash
ERROR: Could not find a version that satisfies the requirement cuda-python<13,>=12.3 (from phlash) (from versions: none)
ERROR: No matching distribution found for cuda-python<13,>=12.3
```

I guess this is simply an unsupported machine, but it would be good to clarify, thanks!

**Comment by hyanwong** [comment]
> Hey Yan, thanks for trying this out! 

No problem: it's great that you made this so easy to install/use, thanks.

Well, it installs now! I tried an easily simulation-based run with `sim_contigs = phlash.sim.stdpopsim_dataset("HomSap", "Zigzag_1S14", {"generic": 3}, options=dict(length_multiplier=0.01))` and it seemed to run through fine, although about 2/3rds though I got:

```
2024-05-17 11:37:38.800 | INFO     | phlash.mcmc:fit:298 - The expected log-predictive density has not improved in the last 100 iterations; exiting.
```

But that's a model-fitting thing, so I guess it's fine, and you can close this issue.

It might be worth specifying a random seed in the examples, so you can get replicable behaviour if people try it out? A word of caution: I think the stdpopsim random seed is set using `seed=XXX`, whereas _msprime_ uses `random_seed=XXX`. If you use `engine.simulate(random_seed=XXX)` I believe that the seed will be ignored, and no error raised, which has caught me out a few times.

**Comment by terhorst** [comment]
Cool, glad it works. The message about terminating early is actually a succesful exit--it just means that the predictive density on a heldout dataset is stable, so the method quits searching for a better optimum to avoid overfitting. 

Let me know if you run into any other issues, or unexpected/unclear behavior. I'm thinking it may be possible to run on a small dataset and get a reasonable estimate even without a GPU, as we discussed at probgen.
